$ = jQuery = require('jquery')
var React = require('react')
var ReactDOM = require('react-dom')
var App = require('./components/app')
let el = document.getElementById('root')
ReactDOM.render(<App />, el)
